# Site settings
baseurl = "https://navdevl.xyz/"
languageCode = "en"
title = "NavDevl"
googleAnalytics = "UA-111593067-1"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
languagecode = "en"
paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "navdevl-xyz"

[params]
    author = "Naveen Honest Raj"
    description = "Navdevl's personal website"
    keywords = "blog,developer,personal"
    info = "Lead Blockchain Engineer"
    shorturl = "navdevl.xyz"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/NavDevl/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/nav_devl/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/naveen-honest-raj-089b08ab/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
